# Generated by Django 6.0.3 on 2026-04-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_category_customuser_product_delete_client_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
    ]
